{"tests": 11, "errors": 0, "results": [{"skipped_msg": null, "error_trace": null, "test_method_name": "test_settings_data_get_status", "failure_trace": null, "test_class_name": "SettingsAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_create_xshop_report", "failure_trace": null, "test_class_name": "XShopAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_xshop_report_generation_with_invalid_id", "failure_trace": null, "test_class_name": "XShopAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_xshop_report_generation_status", "failure_trace": null, "test_class_name": "XShopAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_get_all_notifications_marked", "failure_trace": null, "test_class_name": "NotificationsAPITests", "result": "PASSED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_get_all_notifications", "failure_trace": "Traceback (most recent call last):\n  File \"/Library/Python/2.7/site-packages/pciservicesroast/pciservicesroast/notifications_api_tests/test_notifications_api.py\", line 10, in test_get_all_notifications\n    self.assertEquals(1,2, msg=\"Values do not match\")\nAssertionError: Values do not match\n", "test_class_name": "NotificationsAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_get_notifications_marked_read_by_id", "failure_trace": "Traceback (most recent call last):\n  File \"/Library/Python/2.7/site-packages/pciservicesroast/pciservicesroast/notifications_api_tests/test_notifications_api.py\", line 20, in test_get_notifications_marked_read_by_id\n    self.assertEquals(1,2, msg=\"Values do not match\")\nAssertionError: Values do not match\n", "test_class_name": "NotificationsAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_get_notifications_marked_read_by_invalid_id", "failure_trace": "Traceback (most recent call last):\n  File \"/Library/Python/2.7/site-packages/pciservicesroast/pciservicesroast/notifications_api_tests/test_notifications_api.py\", line 25, in test_get_notifications_marked_read_by_invalid_id\n    self.assertEquals(1,2, msg=\"Values do not match\")\nAssertionError: Values do not match\n", "test_class_name": "NotificationsAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_get_notifications_marked_read_by_unknown_id", "failure_trace": "Traceback (most recent call last):\n  File \"/Library/Python/2.7/site-packages/pciservicesroast/pciservicesroast/notifications_api_tests/test_notifications_api.py\", line 30, in test_get_notifications_marked_read_by_unknown_id\n    self.assertEquals(1,2, msg=\"Values do not match\")\nAssertionError: Values do not match\n", "test_class_name": "NotificationsAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_settings_data_get_status_by_id", "failure_trace": "Traceback (most recent call last):\n  File \"/Library/Python/2.7/site-packages/pciservicesroast/pciservicesroast/settings_api_tests/test_settings_api.py\", line 23, in test_settings_data_get_status_by_id\n    self.assertEquals(1,2, msg=\"Values do not match\")\nAssertionError: Values do not match\n", "test_class_name": "SettingsAPITests", "result": "FAILED"}, {"skipped_msg": null, "error_trace": null, "test_method_name": "test_settings_data_get_status_by_invalid_id", "failure_trace": "Traceback (most recent call last):\n  File \"/Library/Python/2.7/site-packages/pciservicesroast/pciservicesroast/settings_api_tests/test_settings_api.py\", line 28, in test_settings_data_get_status_by_invalid_id\n    self.assertEquals(1,2, msg=\"Values do not match\")\nAssertionError: Values do not match\n", "test_class_name": "SettingsAPITests", "result": "FAILED"}], "skips": 0, "time": "10.4832940102", "failures": 6}